name: Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get tag version
        id: get_version
        run: echo "version=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

      - name: Create release directory
        run: |
          mkdir -p release/custom_components

      - name: Copy integration files
        run: |
          cp -r custom_components/idotmatrix release/custom_components/

      - name: Remove unwanted files
        run: |
          find release/ -name "__pycache__" -type d -exec rm -rf {} + || true
          find release/ -name "*.pyc" -delete || true
          find release/ -name ".DS_Store" -delete || true

      - name: Create zip file
        run: |
          cd release
          zip -r ../idotmatrix-${{ steps.get_version.outputs.version }}.zip custom_components/
          cd ..

      - name: Create GitHub Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create ${{ steps.get_version.outputs.version }} \
            --title "iDotMatrix Display ${{ steps.get_version.outputs.version }}" \
            --notes "## Changes in ${{ steps.get_version.outputs.version }}

          Initial release of the iDotMatrix Display integration for Home Assistant.

          ## Features
          - Bluetooth device discovery and connection
          - Display control through Home Assistant UI
          - Support for text display, brightness control, and display effects
          - Compatible with iDotMatrix LED display devices

          ## Installation

          ### HACS (Recommended)
          1. Add this repository as a custom repository in HACS
          2. Install iDotMatrix Display
          3. Restart Home Assistant

          ### Manual Installation
          1. Download the idotmatrix-${{ steps.get_version.outputs.version }}.zip file
          2. Extract to your custom_components directory
          3. Restart Home Assistant

          ## Requirements
          - Home Assistant 2023.1 or later
          - Bluetooth support on your Home Assistant host
          - iDotMatrix LED display device" \
            idotmatrix-${{ steps.get_version.outputs.version }}.zip
